-- CreateTable
CREATE TABLE `Associados` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `numero_proposta_SBA` INTEGER NOT NULL,
    `matricula_SAERJ` INTEGER NOT NULL,
    `matricula_SBA` INTEGER NOT NULL,
    `situacao` VARCHAR(191) NOT NULL,
    `uf_crm` VARCHAR(191) NOT NULL,
    `crm` INTEGER NOT NULL,
    `nome_completo` VARCHAR(191) NOT NULL,
    `cpf` VARCHAR(191) NOT NULL,
    `sexo` VARCHAR(191) NOT NULL,
    `nome_profissional` VARCHAR(191) NOT NULL,
    `categoria` VARCHAR(191) NOT NULL,
    `cep` VARCHAR(191) NOT NULL,
    `logradouro` VARCHAR(191) NOT NULL,
    `numero` INTEGER NOT NULL,
    `complemento` VARCHAR(191) NOT NULL,
    `bairro` VARCHAR(191) NOT NULL,
    `cidade` VARCHAR(191) NOT NULL,
    `uf` VARCHAR(191) NOT NULL,
    `pais` VARCHAR(191) NOT NULL,
    `telefone_celular` VARCHAR(191) NOT NULL,
    `telefone_residencial` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `nome_instituicao_ensino_graduacao` VARCHAR(191) NOT NULL,
    `ano_conclusao_graduacao` VARCHAR(191) NOT NULL,
    `dayPrevisaoConclusao` VARCHAR(191) NOT NULL,
    `monthPrevisaoConclusao` VARCHAR(191) NOT NULL,
    `yearPrevisaoConclusao` VARCHAR(191) NOT NULL,
    `residencia_mec_cnrm` VARCHAR(191) NOT NULL,
    `nivel_residencia` VARCHAR(191) NOT NULL,
    `nome_hospital_mec` VARCHAR(191) NOT NULL,
    `uf_prm` VARCHAR(191) NOT NULL,
    `comprovante_endereco` VARCHAR(191) NOT NULL,
    `carta_indicacao_2_mrmbros` VARCHAR(191) NOT NULL,
    `declaracao_hospital` VARCHAR(191) NOT NULL,
    `diploma_medicina` VARCHAR(191) NOT NULL,
    `certidao_quitacao_crm` VARCHAR(191) NOT NULL,
    `certificado_conclusao_especializacao` VARCHAR(191) NOT NULL,
    `declaro_verdadeiras` VARCHAR(191) NOT NULL,
    `declaro_quite_SAERJ` VARCHAR(191) NOT NULL,
    `pendencias_SAERJ` VARCHAR(191) NOT NULL,
    `nome_presidente_regional` VARCHAR(191) NOT NULL,
    `sigla_regional` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
