import { z } from 'zod'

export const schemaPagamentos = z.object({
  matricula_saerj: z.string().min(1, { message: 'Campo Obrigatório' }),
  tipo_pagamento: z.string().min(1, { message: 'Campo Obrigatório' }),
  ano_anuidade: z.string(),
  data_pagto_unico: z.string(),
  dayPagtoUnic: z.string(),
  monthPagtoUnic: z.string(),
  yearPagtoUnic: z.string(),
  valor_pagto_unico: z.string(),
  data_pagto_parcela_1: z.string(),
  dayPagtoParc1: z.string(),
  monthPagtoParc1: z.string(),
  yearPagtoParc1: z.string(),
  valor_pagto_parcela_1: z.string(),
  data_pagto_parcela_2: z.string(),
  dayPagtoParc2: z.string(),
  monthPagtoParc2: z.string(),
  yearPagtoParc2: z.string(),
  valor_pagto_parcela_2: z.string(),
  data_pagto_parcela_3: z.string(),
  dayPagtoParc3: z.string(),
  monthPagtoParc3: z.string(),
  yearPagtoParc3: z.string(),
  valor_pagto_parcela_3: z.string(),
})
